### ISSUE TITLE
v1 to-do list

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/nautilus#2]
Let's consider this my ongoing to-do list.

### Colour
- [ ] import palette (needs improvement, maybe using colour generator?)
- [ ] implement named colour variables for branding

### Typography
- [ ] provide font options for headings as well, so headings are more flexible?
- [x] size adjustment (multiplier) for small-caps
- [ ] small-caps option for headings
- [x] spacing on headings: more for xxl, less for xxs
- [ ] wrapper component for headings, maybe choosing the heading style? or use headings as they are?
- [ ] how to overwrite/brand?
- [ ] pull in Harriet proper, please
- [ ] drop-cap option for paragraphs
- [ ] inline items (strong, em)
- [ ] lists
- [ ] links

### Spacing
- [ ] show/hide grid in Nautilus (and element outlines, see code below)
- [x] create variables for spacers that can be applied in CSS
- [ ] show spacers?
- [ ] maybe provide some sort of overall container styling as well?
- [ ] are we using/providing a grid as well?

### General

- [ ] principles
- [ ] documentation of typography, spacing, colour
- [ ] improve visual design of styleguide itself
- [ ] documentation (technical)

### Initial components

- [ ] paragraph
- [ ] heading
- [ ] card
- [ ] navigation
- [ ] button
- [ ] input
- [ ] metadata/tag

```
#___gatsby {	
	z-index: 1;
	position: relative;
}

.--grid--{
    background-size: 8px 8px;
   	background-image: linear-gradient(to bottom, 
   						transparent 1px,
   						transparent 7px,
   						rgba(255,188,222,0.5) 8px);
   	z-index: -1 !important;
}

h1, h2, h3, h4, h5, h6, p {
	//border: 1px solid rgba(150,228,233,0.50);
	background: rgba(150,228,233,0.25);
}
```

**Comment by sarahmonster** [comment]
This list has all been broken out into individual issues, so I think can safely be closed.
